import type { CanvasNode } from "../components/canvas/CanvasDashboard";

/** Starter layout — reset restores this. */
export function createDefaultDashboardNodes(): CanvasNode[] {
  const t = Date.now();
  const nid = (n: number) => `n_${t}_${n}`;
  return [
    {
      id: nid(1),
      type: "widget",
      x: 48,
      y: 48,
      w: 400,
      h: 200,
      widgetKey: "today",
      widgetVariant: "medium",
      widgetSkin: "ios",
      zIndex: 1,
    },
    {
      id: nid(2),
      type: "widget",
      x: 480,
      y: 48,
      w: 400,
      h: 300,
      widgetKey: "tasks",
      widgetVariant: "medium",
      widgetSkin: "ios",
      zIndex: 2,
    },
    {
      id: nid(3),
      type: "widget",
      x: 48,
      y: 280,
      w: 380,
      h: 280,
      widgetKey: "calendar",
      widgetVariant: "medium",
      widgetSkin: "cortex",
      zIndex: 3,
    },
    {
      id: nid(4),
      type: "widget",
      x: 480,
      y: 380,
      w: 400,
      h: 280,
      widgetKey: "mail",
      widgetVariant: "medium",
      widgetSkin: "ios",
      zIndex: 4,
    },
    {
      id: nid(5),
      type: "widget",
      x: 920,
      y: 48,
      w: 360,
      h: 260,
      widgetKey: "spotify",
      widgetVariant: "medium",
      widgetSkin: "ios",
      zIndex: 5,
    },
    {
      id: nid(6),
      type: "widget",
      x: 920,
      y: 340,
      w: 360,
      h: 240,
      widgetKey: "notes",
      widgetVariant: "medium",
      widgetSkin: "notion",
      zIndex: 6,
    },
    {
      id: nid(7),
      type: "widget",
      x: 920,
      y: 600,
      w: 360,
      h: 200,
      widgetKey: "system",
      widgetVariant: "small",
      widgetSkin: "cortex",
      zIndex: 7,
    },
  ];
}
