import type { ComponentType } from "react";
import type { Tab } from "../tab";
import type { WidgetRegistryEntry, WidgetRenderProps } from "./types";
import {
  AutomationsWidget,
  DailyAgendaWidget,
  EmailPreviewWidget,
  FocusBlockWidget,
  GoalsProgressWidget,
  HabitHeatmapWidget,
  HabitsWidget,
  InboxCaptureWidget,
  MiniCalendarWidget,
  MusicWidget,
  NotesWidget,
  QuickTasksWidget,
  SystemStatusWidget,
  TodayOverviewWidget,
  UpcomingWidget,
} from "./widgets";

const WIDGET_COMPONENTS: Record<string, ComponentType<WidgetRenderProps>> = {
  "today-overview": TodayOverviewWidget,
  "daily-agenda": DailyAgendaWidget,
  "quick-tasks": QuickTasksWidget,
  "inbox-capture": InboxCaptureWidget,
  "mini-calendar": MiniCalendarWidget,
  upcoming: UpcomingWidget,
  "goals-progress": GoalsProgressWidget,
  habits: HabitsWidget,
  "habit-heatmap": HabitHeatmapWidget,
  "focus-block": FocusBlockWidget,
  notes: NotesWidget,
  automations: AutomationsWidget,
  "email-preview": EmailPreviewWidget,
  music: MusicWidget,
  "system-status": SystemStatusWidget,
};

export const WIDGET_REGISTRY: WidgetRegistryEntry[] = [
  {
    id: "today-overview",
    name: "Today overview",
    description: "Hero card with greeting, focus, and day stats.",
    category: "today",
    icon: "☀️",
    previewGradient: "linear-gradient(135deg, #6b9cff 0%, #8b7cf6 55%, #c4b5fd 100%)",
    sizes: { minCol: 4, minRow: 2, maxCol: 12, maxRow: 3, defaultCol: 6, defaultRow: 2 },
    defaultSettings: { density: "default" },
    configFields: [{ key: "title", label: "Title", type: "text", placeholder: "Today" }],
  },
  {
    id: "daily-agenda",
    name: "Daily agenda",
    description: "Timeline of events and time blocks.",
    category: "calendar",
    icon: "📅",
    previewGradient: "linear-gradient(135deg, #38bdf8, #6366f1)",
    sizes: { minCol: 3, minRow: 2, maxCol: 6, maxRow: 4, defaultCol: 3, defaultRow: 3 },
    defaultSettings: { density: "default" },
    configFields: [],
  },
  {
    id: "quick-tasks",
    name: "Quick tasks",
    description: "Today list with checkboxes and quick add.",
    category: "tasks",
    icon: "✓",
    previewGradient: "linear-gradient(135deg, #34d399, #10b981)",
    sizes: { minCol: 3, minRow: 2, maxCol: 6, maxRow: 4, defaultCol: 3, defaultRow: 3 },
    defaultSettings: { density: "default", title: "Today" },
    configFields: [
      { key: "title", label: "Title", type: "text" },
      {
        key: "density",
        label: "Density",
        type: "select",
        options: [
          { value: "compact", label: "Compact" },
          { value: "default", label: "Default" },
          { value: "expanded", label: "Expanded" },
        ],
      },
    ],
  },
  {
    id: "inbox-capture",
    name: "Inbox capture",
    description: "Fast capture to inbox.",
    category: "tasks",
    icon: "📥",
    previewGradient: "linear-gradient(135deg, #fbbf24, #f59e0b)",
    sizes: { minCol: 2, minRow: 1, maxCol: 4, maxRow: 2, defaultCol: 2, defaultRow: 1 },
    defaultSettings: { density: "compact" },
    configFields: [],
  },
  {
    id: "mini-calendar",
    name: "Mini calendar",
    description: "Month grid with today highlight.",
    category: "calendar",
    icon: "🗓",
    previewGradient: "linear-gradient(135deg, #818cf8, #a78bfa)",
    sizes: { minCol: 2, minRow: 2, maxCol: 4, maxRow: 3, defaultCol: 3, defaultRow: 2 },
    defaultSettings: { density: "compact" },
    configFields: [],
  },
  {
    id: "upcoming",
    name: "Upcoming",
    description: "Next events and tasks by day group.",
    category: "calendar",
    icon: "⏭",
    previewGradient: "linear-gradient(135deg, #60a5fa, #3b82f6)",
    sizes: { minCol: 2, minRow: 2, maxCol: 4, maxRow: 3, defaultCol: 3, defaultRow: 2 },
    defaultSettings: { density: "compact" },
    configFields: [],
  },
  {
    id: "goals-progress",
    name: "Goals progress",
    description: "Top goals with progress and status.",
    category: "goals",
    icon: "🎯",
    previewGradient: "linear-gradient(135deg, #f472b6, #ec4899)",
    sizes: { minCol: 3, minRow: 2, maxCol: 6, maxRow: 3, defaultCol: 3, defaultRow: 2 },
    defaultSettings: { density: "default", title: "Goals" },
    configFields: [{ key: "title", label: "Title", type: "text" }],
  },
  {
    id: "habits",
    name: "Habits",
    description: "Daily checklist and streaks.",
    category: "habits",
    icon: "🔥",
    previewGradient: "linear-gradient(135deg, #fb923c, #f97316)",
    sizes: { minCol: 3, minRow: 2, maxCol: 6, maxRow: 3, defaultCol: 4, defaultRow: 2 },
    defaultSettings: { density: "default" },
    configFields: [],
  },
  {
    id: "habit-heatmap",
    name: "Habit heatmap",
    description: "Completion grid week or month.",
    category: "habits",
    icon: "▦",
    previewGradient: "linear-gradient(135deg, #22c55e, #16a34a)",
    sizes: { minCol: 3, minRow: 2, maxCol: 8, maxRow: 3, defaultCol: 4, defaultRow: 2 },
    defaultSettings: { density: "default" },
    configFields: [],
  },
  {
    id: "focus-block",
    name: "Focus block",
    description: "Suggested deep work session.",
    category: "today",
    icon: "◎",
    previewGradient: "linear-gradient(135deg, #a78bfa, #7c3aed)",
    sizes: { minCol: 2, minRow: 2, maxCol: 4, maxRow: 3, defaultCol: 3, defaultRow: 2 },
    defaultSettings: { density: "default" },
    configFields: [],
  },
  {
    id: "notes",
    name: "Pinned note",
    description: "Quick note preview.",
    category: "notes",
    icon: "📝",
    previewGradient: "linear-gradient(135deg, #fde68a, #fcd34d)",
    sizes: { minCol: 2, minRow: 1, maxCol: 4, maxRow: 2, defaultCol: 2, defaultRow: 1 },
    defaultSettings: { density: "compact" },
    configFields: [],
  },
  {
    id: "automations",
    name: "Automations",
    description: "Quick actions like Raycast commands.",
    category: "automations",
    icon: "⚡",
    previewGradient: "linear-gradient(135deg, #94a3b8, #64748b)",
    sizes: { minCol: 2, minRow: 2, maxCol: 5, maxRow: 3, defaultCol: 3, defaultRow: 2 },
    defaultSettings: { density: "default" },
    configFields: [],
  },
  {
    id: "email-preview",
    name: "Email preview",
    description: "Priority inbox snippets.",
    category: "email",
    icon: "✉️",
    previewGradient: "linear-gradient(135deg, #38bdf8, #0ea5e9)",
    sizes: { minCol: 3, minRow: 2, maxCol: 6, maxRow: 3, defaultCol: 4, defaultRow: 2 },
    defaultSettings: { density: "default", title: "Mail" },
    configFields: [{ key: "title", label: "Title", type: "text" }],
  },
  {
    id: "music",
    name: "Music",
    description: "Now playing recommendation.",
    category: "music",
    icon: "🎵",
    previewGradient: "linear-gradient(135deg, #f43f5e, #e11d48)",
    sizes: { minCol: 2, minRow: 2, maxCol: 4, maxRow: 2, defaultCol: 2, defaultRow: 2 },
    defaultSettings: { density: "default" },
    configFields: [],
  },
  {
    id: "system-status",
    name: "System status",
    description: "Sync and health indicators.",
    category: "system",
    icon: "◉",
    previewGradient: "linear-gradient(135deg, #cbd5e1, #94a3b8)",
    sizes: { minCol: 2, minRow: 1, maxCol: 4, maxRow: 2, defaultCol: 3, defaultRow: 1 },
    defaultSettings: { density: "compact" },
    configFields: [],
  },
];

export function getWidgetEntry(id: string): WidgetRegistryEntry | undefined {
  return WIDGET_REGISTRY.find((w) => w.id === id);
}

export function getWidgetComponent(id: string): ComponentType<WidgetRenderProps> | undefined {
  return WIDGET_COMPONENTS[id];
}

export function renderWidgetProps(
  instance: { settings: WidgetRenderProps["settings"] },
  onNavigate?: (tab: Tab) => void,
): WidgetRenderProps {
  const density = instance.settings.density ?? "default";
  return {
    density,
    settings: instance.settings,
    compact: density === "compact",
    onNavigate,
  };
}
