-- Task planning: progress, schedule blocks, Google Calendar link
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "progressPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "planStart" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "planEnd" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "syncToCalendar" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "googleCalendarId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "googleEventId" TEXT;
